import { openAdvanced, analyzeAndOpenReport } from './advanced-controls'
import { test, expect } from '@playwright/test'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

test('saved historical comparisons verify scope, keep costs conditional and export safe offline evidence', async ({ page, context }) => {
  const outDir = resolve(`artifacts/product-improvement/analysis-comparison-${Date.now()}`)
  await mkdir(outDir, { recursive: true })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/health', route => route.fulfill({ json: { providerConfigured: false } }))
  await page.goto('/')
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  const products = 'productId,title,market,currency,price,capturedAt\nSKU,Sample charger,US,USD,30,2026-10-06'
  const reviews = 'reviewId,productId,locale,rating,body,reviewedAt\nR1,SKU,en-US,2,charger gets hot,2026-10-06\nR2,SKU,en-US,4,fast charging,2026-10-05'
  for (const [label, csv] of [['商品 CSV', products], ['评论 CSV', reviews]]) await page.getByLabel(label, { exact: true }).setInputFiles({ name: `${label}.csv`, mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: '读取字段', exact: true }).click()
  await page.getByLabel('products-productId').waitFor()
  await page.getByRole('button', { name: '校验并预览' }).click()
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await openAdvanced(page, '高级成本模型')
  const costs = page.getByRole('region', { name: '三情景成本明细' })
  const amounts = { 售价: 30, 综合到岸成本: 10, 平台佣金率: 0, 履约: 0, 广告费率: 0, 仓储分摊: 0, 退货率: 0, 每次退货增量净损失: 0, 单件新增改良成本: 0, 固定启动投入: 100 }
  for (const [label, amount] of Object.entries(amounts)) {
    const item = costs.locator('details').filter({ has: page.getByLabel(`${label}状态`, { exact: true }) })
    await item.locator('summary').click()
    await item.getByLabel(`${label}状态`, { exact: true }).selectOption('included')
    await item.getByLabel(`${label}明细值`, { exact: true }).fill(String(amount))
    if (label === '售价') await item.getByLabel(`${label}来源`, { exact: true }).fill('<script>comparisonAttack()</script>')
    await item.locator('summary').click()
  }
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  const panel = page.getByRole('region', { name: '历史分析比较' })
  await expect(panel.getByRole('button', { name: '核验并比较历史分析' })).toBeDisabled()
  await analyzeAndOpenReport(page)
  await expect(page.getByText('分析存档已保存到本机')).toBeVisible()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  const price = costs.locator('details').filter({ has: page.getByLabel('售价状态', { exact: true }) })
  await price.locator('summary').click()
  await price.getByLabel('售价明细值', { exact: true }).fill('50')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await analyzeAndOpenReport(page)
  await expect(page.locator('.history-list li')).toHaveCount(2)
  const ids = await panel.getByLabel('比较参照运行').locator('option').evaluateAll(options => options.slice(1).map(option => (option as HTMLOptionElement).value))
  await panel.getByLabel('比较参照运行').selectOption(ids[1])
  await panel.getByLabel('比较对照运行').selectOption(ids[0])
  await panel.getByLabel('比较商品').selectOption('SKU')
  await panel.getByRole('button', { name: '核验并比较历史分析' }).click()
  await expect(panel.getByRole('status')).toContainText('相同样本/配置')
  await expect(panel).toContainText('贡献差 +20.00')
  const jsonEvent = page.waitForEvent('download')
  await panel.getByRole('button', { name: '下载历史比较 JSON' }).click()
  const value = JSON.parse(await readFile((await (await jsonEvent).path())!, 'utf8'))
  expect(value.schemaVersion).toBe('qling-analysis-comparison/1')
  expect(value.comparable).toBe(true)
  expect(value.costRows[0].contributionDelta).toBe(20)
  expect(value.rows.every((row: { delta: { mentionCount: number } }) => row.delta.mentionCount === 0)).toBe(true)
  const widths = []
  for (const width of [320, 390, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    const measured = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }))
    expect(measured.scroll).toBe(measured.client)
    widths.push({ width, ...measured })
    if ([390, 1280].includes(width)) await panel.screenshot({ path: `${outDir}/comparison-${width}.png`, style: '.topbar { visibility: hidden; }' })
  }
  const htmlEvent = page.waitForEvent('download')
  await panel.getByRole('button', { name: '下载历史比较 HTML（可打印）' }).click()
  const html = await readFile((await (await htmlEvent).path())!, 'utf8')
  const memo = await context.newPage()
  await memo.setContent(html)
  expect(await memo.locator('script,svg,img,[onclick],[onerror]').count()).toBe(0)
  await expect(memo.locator('body')).toContainText('<script>comparisonAttack()</script>')
  await expect(memo.locator('body')).toContainText(value.digest)
  await memo.setViewportSize({ width: 390, height: 900 })
  await memo.getByRole('heading', { name: '方面预测对照' }).scrollIntoViewIfNeeded()
  await memo.screenshot({ path: `${outDir}/memo-390.png` })
  await memo.emulateMedia({ media: 'print' })
  await expect(memo.getByRole('heading', { name: '完整历史成本假设及来源' })).toHaveCount(2)
  await expect(memo.getByRole('heading', { name: 'thermal · 原文依据' })).toBeVisible()
  await memo.screenshot({ path: `${outDir}/print-390.png`, fullPage: true })
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await panel.getByLabel('比较参照运行').selectOption(ids[1])
  await panel.getByLabel('比较对照运行').selectOption(ids[0])
  await panel.getByLabel('比较商品').selectOption('SKU')
  await panel.getByRole('button', { name: '核验并比较历史分析' }).click()
  await expect(panel).toContainText(value.digest)
  await page.evaluate(async () => {
    const workspaceModule = '/src/domain/workspace.ts'
    const runModule = '/src/domain/analysis-run.ts'
    const analysisModule = '/src/domain/analysis.ts'
    const { workspaceDatabase } = await import(workspaceModule)
    const { createAnalysisRun } = await import(runModule)
    const { buildInsightReport } = await import(analysisModule)
    const workspace = await workspaceDatabase.restore()
    const runs = await workspaceDatabase.listAnalysisRuns(workspace.id)
    const input = structuredClone(runs[0].input)
    input.dataset.reviews[0].body += ' sometimes'
    const run = createAnalysisRun(workspace.id, buildInsightReport(input.dataset), input, 'local')
    await workspaceDatabase.saveAnalysisRun(run)
  })
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(3)
  const changedId = await panel.getByLabel('比较参照运行').locator('option').nth(1).getAttribute('value')
  await panel.getByLabel('比较参照运行').selectOption(ids[1])
  await panel.getByLabel('比较对照运行').selectOption(changedId!)
  await panel.getByLabel('比较商品').selectOption('SKU')
  await panel.getByRole('button', { name: '核验并比较历史分析' }).click()
  await expect(panel.getByRole('status')).toContainText('不可直接比较趋势')
  await expect(panel).toContainText('样本结构变化')
  await expect(panel.locator('tbody td').last()).toContainText('不可直接比较')
  await panel.getByLabel('比较对照运行').selectOption(ids[1])
  await expect(panel.getByRole('button', { name: '下载历史比较 JSON' })).toHaveCount(0)
  await panel.getByRole('button', { name: '核验并比较历史分析' }).click()
  await expect(panel).toContainText('请选择两份不同')
  await page.getByRole('button', { name: /数据准备/ }).click()
  await openAdvanced(page, '仅替换演示评论')
  await page.getByRole('button', { name: '恢复默认数码快充样例' }).click()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(panel).toHaveCount(0)
  expect(errors).toEqual([])
  await writeFile(`${outDir}/render-check.json`, JSON.stringify({ widths, errors, source: 'synthetic snapshots and costs, offline, simulated viewports; no actual improvement verified' }, null, 2), { flag: 'wx' })
  console.log(`Comparison render evidence: ${outDir}`)
})
