import { test, expect, type Page } from '@playwright/test'
import { mkdir, readFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { openAdvanced, analyzeAndOpenReport } from './advanced-controls'

async function download(page: Page, name: string | RegExp) {
  const pending = page.waitForEvent('download')
  await page.getByRole('button', { name }).click()
  return readFile((await (await pending).path())!, 'utf8')
}

test('compliance revisions persist, restore atomically and agree across JSON HTML and native print', async ({ page, context }) => {
  const outDir = resolve(`artifacts/product-improvement/p1-compliance-${Date.now()}`)
  await mkdir(outDir, { recursive: true })
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message))
  await page.route('**/health', route => route.fulfill({ json: { providerConfigured: false } }))
  await page.goto('/')
  const products = 'productId,title,market,currency,price,capturedAt\nSKU,Synthetic charger,US,USD,30,2026-10-06'
  const reviews = 'reviewId,productId,locale,rating,body,reviewedAt\nR1,SKU,en-US,2,charger gets hot,2026-10-06'
  for (const [label, csv] of [['商品 CSV', products], ['评论 CSV', reviews]]) await page.getByLabel(label, { exact: true }).setInputFiles({ name: `${label}.csv`, mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: '读取字段', exact: true }).click()
  await page.getByLabel('products-productId').waitFor()
  await page.getByRole('button', { name: '校验并预览' }).click()
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await analyzeAndOpenReport(page)
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '保存当前报告到历史' })).toHaveCount(0)
  await page.getByRole('button', { name: '查看历史报告' }).click()
  const panel = page.getByRole('region', { name: '合规复核编辑' })
  await expect(panel.getByLabel('合规适用性')).toHaveValue('unknown')
  await panel.getByLabel('合规主题').fill('Synthetic electrical scope')
  await panel.getByLabel('合规复核人').fill('Local reviewer')
  await panel.getByLabel('合规复核理由').fill('<script>syntheticAttack()</script>需要规格资料')
  await panel.getByLabel('合规人工状态').selectOption('confirmed')
  await panel.getByRole('button', { name: '保存合规复核到本机' }).click()
  await expect(panel.getByRole('alert')).toContainText('人工确认需要')
  await panel.getByLabel('合规人工状态').selectOption('pending')
  await panel.getByRole('button', { name: '保存合规复核到本机' }).click()
  await expect(panel.getByRole('status')).toContainText('已保存到本机')
  await expect(page.locator('.print-report .compliance-summary')).toContainText('待复核 1')
  await panel.getByLabel('合规适用性').selectOption('not-applicable')
  await panel.getByLabel('合规人工状态').selectOption('confirmed')
  await panel.getByLabel('合规适用条件').fill('Synthetic conditions, not legal guidance')
  await panel.getByLabel('合规商品事实').fill('Supplier specification, not independently verified')
  await panel.getByLabel('合规来源-title').fill('User supplied source')
  await panel.getByLabel('合规来源-authority').fill('User declaration')
  await panel.getByLabel('合规来源-url').fill('https://example.com/policy')
  await panel.getByLabel('合规来源-checkedAt').fill('2026-10-06')
  await panel.getByLabel('合规来源身份').selectOption('user-provided')
  await panel.getByLabel('合规复核理由').fill('Synthetic manual scope assessment')
  await panel.getByRole('button', { name: '保存合规复核到本机' }).click()
  await expect(page.locator('.print-report .compliance-summary')).toContainText('人工确认记录 1')
  const json = JSON.parse(await download(page, '导出证据 JSON'))
  expect(json.schemaVersion).toBe('1.8')
  expect(json.complianceReview.records).toHaveLength(2)
  expect(json.complianceReview.latest[0].applicability).toBe('not-applicable')
  const html = await download(page, /导出高管备忘录 HTML/)
  expect(html).toContain(json.complianceReview.digest)
  expect(html).toContain('&lt;script&gt;syntheticAttack()&lt;/script&gt;')
  const memo = await context.newPage(); await memo.route('**/*', route => route.abort()); await memo.setContent(html)
  await expect(memo.getByRole('heading', { name: '人工合规复核 · 与系统风险提示分开' })).toBeVisible()
  expect(await memo.evaluate(() => Reflect.has(window, 'syntheticAttack'))).toBe(false)
  await memo.pdf({ path: resolve(outDir, 'compliance-memo.pdf'), format: 'A4', printBackground: true })
  await page.emulateMedia({ media: 'print' })
  await expect(page.locator('.print-report .compliance-summary')).toContainText('修订 #1')
  await expect(page.locator('.print-report .compliance-summary')).toContainText('修订 #2')
  await page.pdf({ path: resolve(outDir, 'compliance-report.pdf'), format: 'A4', printBackground: true }); await page.emulateMedia({ media: 'screen' })
  await openAdvanced(page, '工作区设置')
  const backup = await download(page, '导出工作区 JSON 备份')
  expect(JSON.parse(backup).schemaVersion).toBe('qling-workspace-backup/7')
  await page.reload(); await page.getByRole('button', { name: /决策报告/ }).click(); await page.getByRole('button', { name: '查看历史报告' }).click()
  await expect(page.locator('.print-report .compliance-summary')).toContainText(json.complianceReview.digest)
  await openAdvanced(page, '工作区设置')
  await page.getByLabel('恢复工作区备份', { exact: true }).setInputFiles({ name: 'v7.json', mimeType: 'application/json', buffer: Buffer.from(backup) })
  await page.getByRole('heading', { name: /让数据先通过审查/ }).waitFor()
  await page.getByRole('button', { name: /决策报告/ }).click(); await page.getByRole('button', { name: '查看历史报告' }).click()
  const restored = JSON.parse(await download(page, '导出证据 JSON'))
  expect(restored.analysisRunId).not.toBe(json.analysisRunId)
  expect(restored.complianceReview.records[0].recordDigest).not.toBe(json.complianceReview.records[0].recordDigest)
  expect(restored.complianceReview.confirmed).toBe(1)
  expect(restored.complianceReview.records.map((record: { revision: number }) => record.revision)).toEqual([1, 2])
  await page.setViewportSize({ width: 390, height: 844 }); await panel.scrollIntoViewIfNeeded()
  await page.screenshot({ path: resolve(outDir, 'compliance-390.png'), fullPage: true })
  await panel.screenshot({ path: resolve(outDir, 'compliance-form-390.png') })
  await page.setViewportSize({ width: 1440, height: 900 })
  await panel.screenshot({ path: resolve(outDir, 'compliance-form-1440.png') })
  await page.setViewportSize({ width: 390, height: 844 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await panel.getByLabel('合规事项').selectOption(restored.complianceReview.latest[0].itemId)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.add
    Reflect.set(window, 'restoreComplianceAdd', () => { IDBObjectStore.prototype.add = original })
    IDBObjectStore.prototype.add = function (...args) { if (this.name === 'complianceReviews') throw new DOMException('Quota', 'QuotaExceededError'); return original.apply(this, args) }
  })
  await panel.getByLabel('合规复核理由').fill('Unsaved revision')
  await panel.getByRole('button', { name: '保存合规复核到本机' }).click()
  await expect(panel.getByRole('alert').first()).toContainText('未保存')
  for (const name of ['导出证据 JSON', /导出高管备忘录 HTML/, /打印 \/ 保存 PDF/]) await expect(page.getByRole('button', { name })).toBeDisabled()
  const failed = JSON.parse(await download(page, '下载未保存合规复核备份'))
  expect(failed.records).toHaveLength(3)
  await page.evaluate(() => Reflect.get(window, 'restoreComplianceAdd')())
  await panel.getByRole('button', { name: '重试保存合规复核' }).click()
  await expect(panel.getByRole('status')).toContainText('已保存到本机')
  expect(JSON.parse(await download(page, '导出证据 JSON')).complianceReview.records).toHaveLength(3)
  expect(errors).toEqual([])
  console.log(`P1 compliance render evidence: ${outDir}`)
})

test('four-step shell remains compact and advanced tools stay accessible at 1440 and 390px', async ({ page }) => {
  const outDir = resolve(`artifacts/product-improvement/p1-shell-${Date.now()}`); await mkdir(outDir, { recursive: true })
  await page.route('**/health', route => route.fulfill({ json: { providerConfigured: false } }))
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 900 }); await page.goto('/')
    for (const step of ['数据准备', '市场机会', '证据与风险', '决策报告']) {
      await page.getByRole('button', { name: new RegExp(step) }).click()
      await expect(page.locator('.workspace-utility details')).not.toHaveAttribute('open', '')
      await expect(page.locator('.work-surface h1')).toBeVisible()
      expect((await page.locator('.work-surface h1').boundingBox())!.y).toBeLessThan(width === 390 ? 600 : 410)
      expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      await page.screenshot({ path: resolve(outDir, `${step}-${width}.png`), fullPage: true })
    }
    const summary = page.locator('.workspace-utility summary'); await summary.focus(); await page.keyboard.press('Enter')
    await expect(page.getByRole('checkbox', { name: /同意本次在线处理/ })).toBeVisible()
    await expect(page.getByLabel('恢复工作区备份', { exact: true })).toBeVisible()
  }
  console.log(`P1 shell render evidence: ${outDir}`)
})
