import { openAdvanced, analyzeAndOpenReport } from './advanced-controls'
import { test, expect } from '@playwright/test'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

test('detailed costs restore, isolate products and freeze history across safe JSON/HTML/print exports', async ({ page, context }) => {
  const outDir = resolve(`artifacts/product-improvement/cost-scenarios-${Date.now()}`)
  await mkdir(outDir, { recursive: true })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.route('**/health', route => route.fulfill({ json: { providerConfigured: false } }))
  await page.goto('/')
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  const products = 'productId,title,market,currency,price,capturedAt\nSKU,Sample charger,US,USD,30,2026-10-06\nOTHER,Another charger,US,USD,40,2026-10-06'
  const reviews = 'reviewId,productId,locale,rating,body,reviewedAt\nR1,SKU,en-US,2,charger gets hot,2026-10-06\nR2,OTHER,en-US,2,charger gets hot,2026-10-06'
  for (const [label, csv] of [['商品 CSV', products], ['评论 CSV', reviews]]) await page.getByLabel(label, { exact: true }).setInputFiles({ name: `${label}.csv`, mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: '读取字段', exact: true }).click()
  await page.getByLabel('products-productId').waitFor()
  await page.getByRole('button', { name: '校验并预览' }).click()
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await openAdvanced(page, '高级成本模型')
  const panel = page.getByRole('region', { name: '三情景成本明细' })
  const baseline = { 售价: 50, 综合到岸成本: 20, 平台佣金率: 0.15, 履约: 4, 广告费率: 0.1, 仓储分摊: 0.5, 退货率: 0.1, 每次退货增量净损失: 10, 单件新增改良成本: 0, 固定启动投入: 1200 }
  for (const kind of ['baseline', 'improvement', 'stress']) {
    await panel.getByLabel('编辑成本情景').selectOption(kind)
    for (const [label, amount] of Object.entries(baseline)) {
      const item = panel.locator('details').filter({ has: page.getByLabel(`${label}状态`, { exact: true }) })
      await item.locator('summary').click()
      await item.getByLabel(`${label}状态`, { exact: true }).selectOption('included')
      await item.getByLabel(`${label}明细值`, { exact: true }).fill(String(kind === 'improvement' && label === '退货率' ? 0.02 : kind === 'stress' && label === '广告费率' ? 0.2 : amount))
      if (label === '综合到岸成本') await item.getByLabel(`${label}来源`, { exact: true }).fill('<script>syntheticCostAttack()</script>')
      await item.locator('summary').click()
    }
  }
  await expect(panel.getByRole('article', { name: '基线贡献结果' })).toContainText('USD 12.00')
  await expect(panel.getByRole('article', { name: '改良贡献结果' })).toContainText('USD 12.80')
  await expect(panel.getByRole('article', { name: '压力贡献结果' })).toContainText('USD 7.00')
  await expect(page.getByText('已保存到本机；不会上传或包含 API 密钥')).toBeVisible()
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await expect(panel.getByRole('article', { name: '基线贡献结果' })).toContainText('USD 12.00')
  await page.getByLabel('测算商品', { exact: true }).selectOption('OTHER')
  await expect(panel.getByRole('article', { name: '基线贡献结果' })).toContainText('单件贡献：未计算')
  await page.getByLabel('测算商品', { exact: true }).selectOption('SKU')
  await expect(panel.getByRole('article', { name: '基线贡献结果' })).toContainText('USD 12.00')
  const sensitivity = panel.getByRole('region', { name: '成本敏感性分析' })
  await sensitivity.getByRole('button', { name: '确认启用敏感性分析' }).click()
  await expect(sensitivity.getByRole('img')).toHaveAttribute('aria-label', '售价变化下三情景贡献曲线')
  await sensitivity.getByLabel('敏感性下限').fill('10')
  await sensitivity.getByLabel('敏感性上限').fill('60')
  await sensitivity.locator('summary').press('Enter')
  await expect(sensitivity.locator('tbody tr').first()).toContainText('非正贡献')
  await sensitivity.getByLabel('敏感性变化参数').selectOption('adRate')
  await sensitivity.getByLabel('敏感性上限').fill('1.1')
  await expect(sensitivity.getByRole('alert')).toContainText('此次修改未保存')
  await sensitivity.getByLabel('敏感性变化参数').selectOption('price')
  const widths = []
  for (const width of [320, 390, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    const measurement = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }))
    expect(measurement.scroll).toBe(measurement.client)
    widths.push({ width, ...measurement })
    if ([390, 1280].includes(width)) {
      await panel.locator('.cost-comparison').screenshot({ path: `${outDir}/comparison-${width}.png`, style: '.topbar { visibility: hidden; }' })
      await sensitivity.locator('.sensitivity-axis').screenshot({ path: `${outDir}/sensitivity-${width}.png`, style: '.topbar { visibility: hidden; }' })
    }
  }
  await panel.locator('details').first().locator('summary').press('Enter')
  await panel.getByLabel('售价明细值', { exact: true }).fill('-1')
  await expect(panel.getByRole('alert')).toContainText('此次无效数值未保存')
  await expect(panel.getByLabel('售价明细值', { exact: true })).toHaveValue('50')
  await panel.getByLabel('售价明细值', { exact: true }).fill('50')
  await page.setViewportSize({ width: 390, height: 900 })
  await panel.locator('details').first().screenshot({ path: `${outDir}/editor-390.png`, style: '.topbar { visibility: hidden; }' })
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await analyzeAndOpenReport(page)
  await expect(page.getByText('分析存档已保存到本机')).toBeVisible()
  const jsonEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const payload = JSON.parse(await readFile((await (await jsonEvent).path())!, 'utf8'))
  expect(payload.schemaVersion).toBe('1.5')
  expect(payload.costSensitivity.axes[0].curves[0].points[0].contribution).toBeLessThan(0)
  expect(payload.costSensitivity.axes[0].curves[0].points[0].breakEvenUnits).toBeNull()
  expect(payload.costComparison[0].result.contributionPerUnit).toBe(12)
  const backupEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出工作区 JSON 备份' }).click()
  const backupText = await readFile((await (await backupEvent).path())!, 'utf8')
  expect(JSON.parse(backupText).workspace.costSets).toBeTruthy()
  expect(JSON.parse(backupText).analysisRuns[0].input.costSet).toBeTruthy()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await panel.getByLabel('编辑成本情景').selectOption('baseline')
  await panel.locator('details').first().locator('summary').click()
  await panel.getByLabel('售价明细值', { exact: true }).fill('60')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  const historicalEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const historical = JSON.parse(await readFile((await (await historicalEvent).path())!, 'utf8'))
  expect(historical.costComparison[0].scenarioDigest).toBe(payload.costComparison[0].scenarioDigest)
  expect(historical.costSet.scenarios[0].price.value).toBe(50)
  expect(historical.costSensitivity.digest).toBe(payload.costSensitivity.digest)
  const htmlEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /导出高管备忘录/ }).click()
  const html = await readFile((await (await htmlEvent).path())!, 'utf8')
  for (const scenario of historical.costComparison) expect(html).toContain(scenario.scenarioDigest)
  expect(html).toContain(historical.costSensitivity.digest)
  const memo = await context.newPage()
  await memo.setContent(html)
  expect(await memo.locator('script,[onerror]').count()).toBe(0)
  await memo.getByRole('heading', { name: '三情景成本假设与贡献' }).scrollIntoViewIfNeeded()
  await memo.screenshot({ path: `${outDir}/memo.png` })
  await memo.getByRole('heading', { name: '成本敏感性条件点' }).scrollIntoViewIfNeeded()
  await memo.screenshot({ path: `${outDir}/sensitivity-memo.png` })
  await page.emulateMedia({ media: 'print' })
  const summary = page.getByRole('region', { name: '明细贡献测算报告' })
  await expect(summary).toBeVisible()
  await expect(summary).toContainText(historical.costComparison[0].scenarioDigest)
  await expect(summary).toContainText(historical.costSensitivity.digest)
  await summary.locator('dl > div').first().screenshot({ path: `${outDir}/print-scope-390.png` })
  await summary.locator('.sensitivity-axis').first().locator('svg').screenshot({ path: `${outDir}/sensitivity-print-390.png` })
  await page.emulateMedia({ media: 'screen' })
  await page.getByRole('button', { name: /数据准备/ }).click()
  await openAdvanced(page, '仅替换演示评论')
  await page.getByRole('button', { name: '恢复默认数码快充样例' }).click()
  await page.getByLabel('恢复工作区备份').setInputFiles({ name: 'cost-backup.json', mimeType: 'application/json', buffer: Buffer.from(backupText) })
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await expect(panel.getByRole('article', { name: '基线贡献结果' })).toContainText('USD 12.00')
  await expect(sensitivity.getByLabel('敏感性下限')).toHaveValue('10')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(page.getByRole('region', { name: '明细贡献测算报告' })).toContainText(historical.costComparison[0].scenarioDigest)
  await expect(page.getByRole('region', { name: '明细贡献测算报告' })).toContainText(historical.costSensitivity.digest)
  expect(errors).toEqual([])
  await writeFile(`${outDir}/render-check.json`, JSON.stringify({ outDir, widths, errors, source: 'synthetic costs, offline only, simulated viewports and print', digests: historical.costComparison.map((scenario: { scenarioDigest: string }) => scenario.scenarioDigest) }, null, 2), { flag: 'wx' })
  console.log(`Cost render evidence: ${outDir}`)
})
