import { openAdvanced, analyzeAndOpenReport } from './advanced-controls'
import { expect, test, type Page } from '@playwright/test'
import { readFile } from 'node:fs/promises'

const products = 'ASIN,title,market,currency,price,capturedAt,rating,reviewCount,sourceUrl\nMY-ASIN,My charger,US,USD,30,2026-10-01,,,\nEU-SKU,EU charger,EU,EUR,40,2026-10-01,,,'
const reviews = 'reviewId,ASIN,locale,rating,body,reviewedAt,verifiedPurchase,sourceUrl\nR1,MY-ASIN,en-US,2,charger gets hot,2026-10-02,,\nR2,EU-SKU,en-US,2,charger gets hot,2026-10-02,,'

async function readFields(page: Page, reviewCsv = reviews, productCsv = products) {
  await page.getByLabel('商品 CSV', { exact: true }).setInputFiles({ name: 'my-products.csv', mimeType: 'text/csv', buffer: Buffer.from(productCsv) })
  await page.getByLabel('评论 CSV', { exact: true }).setInputFiles({ name: 'my-reviews.csv', mimeType: 'text/csv', buffer: Buffer.from(reviewCsv) })
  await page.getByRole('button', { name: '读取字段', exact: true }).click()
  await expect(page.getByLabel('products-productId')).toHaveValue('ASIN')
  await page.getByRole('button', { name: '校验并预览' }).click()
}

async function importData(page: Page) {
  await readFields(page)
  await expect(page.getByText('预览：2 款商品 / 2 条评论 / 去重 0 条')).toBeVisible()
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await expect(page.getByText('已保存到本机；不会上传或包含 API 密钥')).toBeVisible()
}

test.beforeEach(async ({ page }) => {
  await page.route('**/health', (route) => route.fulfill({ json: { providerConfigured: false } }))
  await page.goto('/')
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByRole('button', { name: '读取字段', exact: true })).toBeDisabled()
  await expect(page.getByLabel('商品 CSV', { exact: true })).toBeEnabled()
})

test('real seller import, nullable costs, refresh restore and backup/report export', async ({ page }) => {
  await importData(page)
  await page.getByRole('button', { name: /开始分析/ }).click()
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('平台费率', { exact: true })).toHaveValue('')
  await page.getByLabel('到岸成本', { exact: true }).fill('10')
  await page.getByLabel('平台费率', { exact: true }).fill('10')
  await page.getByLabel('广告费率', { exact: true }).fill('5')
  await page.getByLabel('固定启动成本', { exact: true }).fill('0')
  await expect(page.getByText('0 件', { exact: true })).toBeVisible()
  await expect(page.getByText('已保存到本机；不会上传或包含 API 密钥')).toBeVisible()
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('10')
  await expect(page.getByLabel('固定启动成本', { exact: true })).toHaveValue('0')
  const backupEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出工作区 JSON 备份' }).click()
  const backup = await backupEvent
  const content = await readFile((await backup.path())!, 'utf8')
  const snapshot = JSON.parse(content).workspace
  expect(snapshot.dataset.products[0].reviewCount).toBeNull()
  expect(snapshot.dataset.reviews[0].verifiedPurchase).toBeNull()
  expect(snapshot.pricing.fixedLaunchCost).toBe(0)
  expect(content).not.toMatch(/apiKey|authorization|accessToken/i)
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  const reportEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const exported = JSON.parse(await readFile((await (await reportEvent).path())!, 'utf8'))
  expect(exported.category).toBe('用户商品集合')
  expect(exported.report.provenance.reviews).toBe('user-provided')
  expect(exported.report.complianceRisks).toEqual([])
  await page.getByRole('button', { name: /数据准备/ }).click()
  await openAdvanced(page, '仅替换演示评论')
  await page.getByRole('button', { name: '恢复默认数码快充样例' }).click()
  await page.getByLabel('恢复工作区备份').setInputFiles({ name: 'backup.json', mimeType: 'application/json', buffer: Buffer.from(content) })
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
})

test('human review preserves prediction history, updates confirmed statistics and survives backup restore', async ({ page }) => {
  await importData(page)
  await page.getByRole('button', { name: /开始分析/ }).click()
  await expect(page.getByLabel('到岸成本', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.getByRole('button', { name: '查看历史报告' })).toBeEnabled()
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  const panel = page.getByRole('region', { name: '人工复核', exact: true })
  await expect(panel.getByText('人工接受 0 · 人工驳回 0 · 待复核 2', { exact: true })).toBeVisible()
  const target = panel.locator('.review-target').first()
  await expect(target.getByRole('button', { name: '接受引用与方面' })).toBeDisabled()
  await target.getByLabel('确认情绪').selectOption('mixed')
  await target.getByLabel('复核理由（必填）').fill('冷热体验混合，需样机验证')
  await target.getByRole('button', { name: '接受引用与方面' }).click()
  await expect(panel.getByText('人工接受 1 · 人工驳回 0 · 待复核 1', { exact: true })).toBeVisible()
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const first = JSON.parse(await readFile((await (await event).path())!, 'utf8'))
  expect(first.report.themes[0].sentiment).toBe('negative')
  expect(first.humanReview.statistics[0].sample).toMatchObject({ basis: 'human-reviewed', sampleCount: 1, mentionCount: 1, negativeCount: 0, mixedCount: 1 })
  await target.getByLabel('复核理由（必填）').fill('<script>not-executable</script> 原文不足以支持该方面')
  await target.getByRole('button', { name: '驳回引用与方面' }).click()
  await expect(panel.getByText('人工接受 0 · 人工驳回 1 · 待复核 1', { exact: true })).toBeVisible()
  const reportEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const exported = JSON.parse(await readFile((await (await reportEvent).path())!, 'utf8'))
  expect(exported.evidenceDigest).toBe(first.evidenceDigest)
  expect(exported.scenarioDigest).toBe(first.scenarioDigest)
  expect(exported.humanReview.records).toHaveLength(2)
  expect(exported.humanReview.digest).not.toBe(first.humanReview.digest)
  const htmlEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /导出高管备忘录/ }).click()
  const html = await readFile((await (await htmlEvent).path())!, 'utf8')
  expect(html).toContain(exported.humanReview.digest)
  expect(html).not.toContain('<script>not-executable</script>')
  expect(html).toContain('&lt;script&gt;not-executable&lt;/script&gt;')
  const backupEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出工作区 JSON 备份' }).click()
  const backup = await readFile((await (await backupEvent).path())!, 'utf8')
  expect(JSON.parse(backup).schemaVersion).toBe('qling-workspace-backup/4')
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(panel.getByText('人工接受 0 · 人工驳回 1 · 待复核 1', { exact: true })).toBeVisible()
  await page.getByLabel('恢复工作区备份').setInputFiles({ name: 'review-backup.json', mimeType: 'application/json', buffer: Buffer.from(backup) })
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(panel.getByText('人工接受 0 · 人工驳回 1 · 待复核 1', { exact: true })).toBeVisible()
  await panel.getByText('查看全部复核修订（2 条）', { exact: true }).click()
  await expect(panel.getByText(/修订 1 .*接受\/混合/)).toBeVisible()
})

test('failed human review is excluded, downloadable and retryable without losing the prediction', async ({ page }) => {
  await importData(page)
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await analyzeAndOpenReport(page)
  await expect(page.getByText('分析存档已保存到本机')).toBeVisible()
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.add
    Reflect.set(window, 'restoreReviewAdd', () => { IDBObjectStore.prototype.add = original })
    IDBObjectStore.prototype.add = function (...args) {
      if (this.name === 'humanReviews') throw new DOMException('Quota full', 'QuotaExceededError')
      return original.apply(this, args)
    }
  })
  const panel = page.getByRole('region', { name: '人工复核', exact: true })
  const target = panel.locator('.review-target').first()
  await target.getByLabel('复核理由（必填）').fill('上下文不足，需进一步核对')
  await target.getByRole('button', { name: '驳回引用与方面' }).click()
  await expect(panel.getByText(/复核未保存：存储失败/)).toBeVisible()
  await expect(panel.getByText('人工接受 0 · 人工驳回 0 · 待复核 2', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '导出证据 JSON' })).toBeDisabled()
  const downloadEvent = page.waitForEvent('download')
  await panel.getByRole('button', { name: '下载未保存复核 JSON' }).click()
  const payload = JSON.parse(await readFile((await (await downloadEvent).path())!, 'utf8'))
  expect(payload.saved).toBe(false)
  expect(payload.record.reason).toBe('上下文不足，需进一步核对')
  expect(payload.analysisRun.report.themes[0].sentiment).toBe('negative')
  await page.evaluate(() => Reflect.get(window, 'restoreReviewAdd')())
  await panel.getByRole('button', { name: '重试保存复核' }).click()
  await expect(panel.getByText('人工接受 0 · 人工驳回 1 · 待复核 1', { exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '导出证据 JSON' })).toBeEnabled()
})

test('invalid preview preserves current workspace and cost drafts stay isolated by scope', async ({ page }) => {
  await importData(page)
  await readFields(page, reviews.replace('R1,MY-ASIN', 'R1,missing'))
  await expect(page.getByRole('alert')).toContainText('商品不存在')
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await page.getByLabel('到岸成本', { exact: true }).fill('12')
  await page.getByRole('button', { name: '欧盟', exact: true }).click()
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('')
  await page.getByLabel('到岸成本', { exact: true }).fill('20')
  await page.getByRole('button', { name: '全部市场', exact: true }).click()
  await expect(page.getByLabel('测算商品', { exact: true })).toHaveValue('EU-SKU')
  await page.getByLabel('测算商品', { exact: true }).selectOption('MY-ASIN')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('12')
  await page.getByRole('button', { name: '欧盟', exact: true }).click()
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('20')
})

test('storage failure is visible and unsaved memory can still be backed up', async ({ page }) => {
  await page.evaluate(() => {
    IDBObjectStore.prototype.put = function () { throw new DOMException('Quota full', 'QuotaExceededError') }
  })
  await readFields(page)
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await expect(page.getByText(/未保存：存储失败或额度不足/)).toBeVisible()
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出工作区 JSON 备份' }).click()
  expect((await event).suggestedFilename()).toBe('qling-workspace-backup-v4.json')
})

test('worker handles 10,000 reviews without silent truncation', async ({ page }) => {
  const header = reviews.split('\n')[0]
  const rows = Array.from({ length: 10_000 }, (_, index) => `R${index},MY-ASIN,en-US,2,charger gets hot,2026-10-02,,`)
  await readFields(page, header + '\n' + rows.join('\n'))
  await expect(page.getByText('预览：2 款商品 / 10000 条评论 / 去重 0 条')).toBeVisible()
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await expect(page.getByRole('button', { name: '运行百炼增强' })).toBeDisabled()
  await expect(page.getByText(/在线分析按商品\/市场串行分批，每批最多 50 条/)).toBeVisible()
})

test('same-currency product costs survive product/market/demo switches and export their identity', async ({ page }) => {
  await readFields(page, reviews, products + '\nMY-SECOND,Second charger,US,USD,50,2026-10-01,,,')
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await expect(page.getByLabel('测算商品', { exact: true })).toHaveValue('MY-ASIN')
  await page.getByLabel('到岸成本', { exact: true }).fill('10')
  await page.getByLabel('平台费率', { exact: true }).fill('10')
  await page.getByLabel('广告费率', { exact: true }).fill('0')
  await page.getByLabel('固定启动成本', { exact: true }).fill('0')
  await page.getByLabel('测算商品', { exact: true }).selectOption('MY-SECOND')
  await expect(page.getByLabel('售价', { exact: true })).toHaveValue('50')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('')
  await page.getByLabel('到岸成本', { exact: true }).fill('20')
  await page.getByRole('button', { name: '美国', exact: true }).click()
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('20')
  await page.getByLabel('测算商品', { exact: true }).selectOption('MY-ASIN')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('10')
  await expect(page.getByLabel('广告费率', { exact: true })).toHaveValue('0')
  await page.getByRole('button', { name: '欧盟', exact: true }).click()
  await expect(page.getByLabel('测算商品', { exact: true })).toHaveValue('EU-SKU')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('')
  await page.getByRole('button', { name: '全部市场', exact: true }).click()
  await page.getByLabel('测算商品', { exact: true }).selectOption('MY-SECOND')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('20')
  await expect(page.getByText('已保存到本机；不会上传或包含 API 密钥')).toBeVisible()
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await expect(page.getByLabel('测算商品', { exact: true })).toHaveValue('MY-SECOND')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('20')
  await page.getByLabel('测算商品', { exact: true }).selectOption('MY-ASIN')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  const reportEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const exported = JSON.parse(await readFile((await (await reportEvent).path())!, 'utf8'))
  expect(exported.pricingTarget).toEqual({ productId: 'MY-ASIN', market: 'US', currency: 'USD' })
  expect(exported.scenarioIntegrity.schemaVersion).toBe('qling-pricing-scenario/2')
  expect(exported.pricingAssumptions.landedCost).toBe(10)
  const memoEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /导出高管备忘录/ }).click()
  const memo = await readFile((await (await memoEvent).path())!, 'utf8')
  expect(memo).toContain('MY-ASIN')
  expect(memo).toContain(exported.scenarioDigest.toUpperCase())
  await page.getByRole('button', { name: /数据准备/ }).click()
  await page.getByRole('button', { name: /宠物智能喂食器/ }).click()
  await page.getByRole('button', { name: '恢复最近真实工作区' }).click()
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await expect(page.getByLabel('测算商品', { exact: true })).toHaveValue('MY-ASIN')
  await expect(page.getByLabel('到岸成本', { exact: true })).toHaveValue('10')
})

test('analysis history retains original costs, timestamps and fingerprints across refresh and backup restore', async ({ page }) => {
  await importData(page)
  await page.getByRole('button', { name: /开始分析/ }).click()
  await page.getByLabel('到岸成本', { exact: true }).fill('10')
  await page.getByLabel('平台费率', { exact: true }).fill('10')
  await page.getByLabel('广告费率', { exact: true }).fill('0')
  await page.getByLabel('固定启动成本', { exact: true }).fill('0')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await analyzeAndOpenReport(page)
  await expect(page.locator('.history-list li')).toHaveCount(2)
  await expect(page.getByText('分析存档已保存到本机')).toBeVisible()
  const originalEvent = page.waitForEvent('download')
  await page.locator('.history-list li').first().getByRole('button', { name: '下载分析存档' }).click()
  const original = JSON.parse(await readFile((await (await originalEvent).path())!, 'utf8'))
  expect(original.input.pricingScenario.assumptions.landedCost).toBe(10)
  await page.getByRole('button', { name: /市场机会/ }).click()
  await openAdvanced(page, '高级成本模型')
  await page.getByLabel('到岸成本', { exact: true }).fill('99')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.locator('.history-list li').first().getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  const historyEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const archived = JSON.parse(await readFile((await (await historyEvent).path())!, 'utf8'))
  expect(archived.pricingAssumptions.landedCost).toBe(10)
  expect(archived.report.generatedAt).toBe(original.report.generatedAt)
  expect(archived.archiveDigest).toBe(original.archiveDigest)
  expect(archived.evidenceDigest).toBe(original.evidenceDigest)
  const memoEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /导出高管备忘录/ }).click()
  const html = await readFile((await (await memoEvent).path())!, 'utf8')
  expect(html).toContain('历史快照')
  expect(html).toContain(original.archiveDigest)
  await page.getByRole('button', { name: '返回当前报告' }).click()
  await expect(page.locator('.archive-stamp')).toHaveCount(0)
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(2)
  await page.locator('.history-list li').first().getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(page.locator('.archive-stamp')).toContainText(original.archiveDigest)
  const backupEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出工作区 JSON 备份' }).click()
  const backup = await readFile((await (await backupEvent).path())!, 'utf8')
  expect(JSON.parse(backup).analysisRuns).toHaveLength(2)
  await page.getByRole('button', { name: /数据准备/ }).click()
  await openAdvanced(page, '仅替换演示评论')
  await page.getByRole('button', { name: '恢复默认数码快充样例' }).click()
  await page.getByLabel('恢复工作区备份').setInputFiles({ name: 'archive.json', mimeType: 'application/json', buffer: Buffer.from(backup) })
  await expect(page.getByText('用户工作区 · my-products.csv').first()).toBeVisible()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(2)
  const restoredEvent = page.waitForEvent('download')
  await page.locator('.history-list li').first().getByRole('button', { name: '下载分析存档' }).click()
  const restored = JSON.parse(await readFile((await (await restoredEvent).path())!, 'utf8'))
  expect(restored.id).not.toBe(original.id)
  expect(restored.evidenceDigest).toBe(original.evidenceDigest)
  expect(restored.report.generatedAt).toBe(original.report.generatedAt)
})

test('failed history storage stays visible and can be downloaded and retried', async ({ page }) => {
  await importData(page)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.add
    Object.defineProperty(window, 'restoreHistoryAdd', { value: () => { IDBObjectStore.prototype.add = original } })
    IDBObjectStore.prototype.add = function (...args) {
      if (this.name === 'analysisRuns') throw new DOMException('Quota full', 'QuotaExceededError')
      return original.apply(this, args)
    }
  })
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await analyzeAndOpenReport(page)
  await expect(page.getByText(/历史未保存：存储失败/)).toBeVisible()
  await expect(page.locator('.history-list li')).toContainText('未保存，可重试')
  const backupEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载分析存档' }).click()
  const run = JSON.parse(await readFile((await (await backupEvent).path())!, 'utf8'))
  expect(run.schemaVersion).toBe('qling-analysis-run/1')
  await page.evaluate(() => Reflect.get(window, 'restoreHistoryAdd')())
  await page.getByRole('button', { name: '重试保存历史' }).click()
  await expect(page.getByText('分析存档已保存到本机')).toBeVisible()
  await expect(page.locator('.history-list li')).toContainText('已保存')
})

test('invalid v2 quotes fall back without saving an online finding', async ({ page }) => {
  await importData(page)
  await page.route('**/health', (route) => route.fulfill({ json: { providerConfigured: true }, headers: { 'Access-Control-Allow-Origin': '*' } }))
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('百炼可用')).toBeVisible()
  await page.route('**/api/analyze', (route) => route.fulfill({ headers: { 'Access-Control-Allow-Origin': '*' }, json: { protocolVersion: 2, choices: [{ message: { content: JSON.stringify({ themes: [{ id: 'forged', aspectId: 'thermal', productId: 'MY-ASIN', market: 'US', label: '无效在线主题', sentiment: 'negative', quotes: [{ reviewId: 'R1', field: 'body', quote: 'invented evidence', start: 0, end: 16 }] }], complianceRisks: [] }) } }] } }))
  await page.getByRole('checkbox', { name: /同意本次在线处理/ }).check()
  await page.getByRole('button', { name: '运行百炼增强' }).click()
  await expect(page.getByText(/模型引用未通过原文锚点校验/)).toBeVisible()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await expect(page.locator('.history-list li')).toContainText('在线失败后的本地回退')
  const downloadEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载分析存档' }).click()
  const run = JSON.parse(await readFile((await (await downloadEvent).path())!, 'utf8'))
  expect(run.report.providerMode).toBe('fixture')
  expect(run.report.themes.some((theme: { id: string }) => theme.id === 'forged')).toBe(false)
})

test('cancelled online batches preserve completed scope and never start remaining work', async ({ page }) => {
  const csv = 'reviewId,ASIN,locale,rating,body,reviewedAt,verifiedPurchase,sourceUrl\n' + Array.from({ length: 101 }, (_, index) => `R${index},MY-ASIN,en-US,2,charger gets hot,2026-10-02,,`).join('\n')
  await readFields(page, csv, products.split('\n').slice(0, 2).join('\n'))
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await expect(page.getByText('已保存到本机；不会上传或包含 API 密钥')).toBeVisible()
  await page.route('**/health', (route) => route.fulfill({ json: { providerConfigured: true }, headers: { 'Access-Control-Allow-Origin': '*' } }))
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('百炼可用')).toBeVisible()
  let calls = 0
  let release = () => {}
  const blocked = new Promise<void>((resolve) => { release = resolve })
  await page.route('**/api/analyze', async (route) => {
    calls += 1
    if (calls === 2) { await blocked; await route.abort(); return }
    const input = route.request().postDataJSON().dataset
    await route.fulfill({ headers: { 'Access-Control-Allow-Origin': '*' }, json: { protocolVersion: 2, model: 'batch-e2e', choices: [{ message: { content: JSON.stringify({ themes: [{ id: 'heat', aspectId: 'thermal', productId: 'MY-ASIN', market: 'US', label: '发热', sentiment: 'negative', quotes: input.reviews.map((review: { reviewId: string }) => ({ reviewId: review.reviewId, field: 'body', quote: 'charger gets hot', start: 0, end: 16 })) }], complianceRisks: [] }) } }] } })
  })
  await page.getByRole('checkbox', { name: /同意本次在线处理/ }).check()
  await page.getByRole('button', { name: '运行百炼增强' }).click()
  await expect.poll(() => calls).toBe(2)
  await page.getByRole('button', { name: '取消在线分析' }).click()
  await expect(page.getByText(/已取消 · 成功 1\/3 批/)).toBeVisible()
  release()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  const download = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const exported = JSON.parse(await readFile((await (await download).path())!, 'utf8'))
  expect(exported.report.batchRun.status).toBe('cancelled')
  expect(exported.report.themes[0].mentions).toBe(50)
  expect(exported.report.themes[0].sampleStats[0].sampleCount).toBe(50)
  expect(exported.evidencePayload).toContain('R100')
  expect(calls).toBe(2)
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(page.getByText(/已取消 · 成功 1\/3 批/)).toBeVisible()
})

test('partial online failure keeps exact scope across report exports and does not retry bad quotes', async ({ page }) => {
  await importData(page)
  await page.route('**/health', (route) => route.fulfill({ json: { providerConfigured: true }, headers: { 'Access-Control-Allow-Origin': '*' } }))
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('百炼可用')).toBeVisible()
  let calls = 0
  await page.route('**/api/analyze', async (route) => {
    calls += 1
    const input = route.request().postDataJSON().dataset
    const product = input.products[0]
    await route.fulfill({ headers: { 'Access-Control-Allow-Origin': '*' }, json: { protocolVersion: 2, model: 'partial-model', choices: [{ message: { content: JSON.stringify({ themes: [{ id: 'heat', aspectId: 'thermal', productId: product.productId, market: product.market, label: '发热', sentiment: 'negative', quotes: [{ reviewId: input.reviews[0].reviewId, field: 'body', quote: product.market === 'EU' ? 'invented' : 'charger gets hot', start: 0, end: 16 }] }], complianceRisks: [] }) } }] } })
  })
  await page.getByRole('checkbox', { name: /同意本次在线处理/ }).check()
  await page.getByRole('button', { name: '运行百炼增强' }).click()
  await expect(page.getByText(/部分完成 · 成功 1\/2 批/)).toBeVisible()
  expect(calls).toBe(2)
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name: '导出证据 JSON' }).click()
  const exported = JSON.parse(await readFile((await (await event).path())!, 'utf8'))
  expect(exported.report.providerMode).toBe('bailian')
  expect(exported.report.dataQuality.totalReviews).toBe(1)
  expect(exported.report.batchRun.batches[1]).toMatchObject({ status: 'failed', error: 'evidence-contract', reviewIds: ['R2'], attempts: 1 })
  const htmlEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: /导出高管备忘录/ }).click()
  const html = await readFile((await (await htmlEvent).path())!, 'utf8')
  expect(html).toContain('部分完成 · 成功 1/2 批')
  expect(html).toContain('评论 ID：R2')
  await page.emulateMedia({ media: 'print' })
  const printedScope = page.locator('.print-report .batch-print-only')
  await expect(printedScope).toBeVisible()
  await expect(printedScope).toContainText('评论 ID：R2')
})

test('mocked online and fallback runs preserve distinct modes, stale responses create no history', async ({ page }) => {
  await importData(page)
  await page.route('**/health', (route) => route.fulfill({ json: { providerConfigured: true }, headers: { 'Access-Control-Allow-Origin': '*' } }))
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await expect(page.getByText('百炼可用')).toBeVisible()
  let call = 0
  let phase = 1
  let releaseThird: () => void = () => {}
  const thirdResponse = new Promise<void>((resolve) => { releaseThird = resolve })
  await page.route('**/api/analyze', async (route) => {
    call += 1
    if (phase === 2) { await route.fulfill({ status: 403, body: 'unavailable', headers: { 'Access-Control-Allow-Origin': '*' } }); return }
    if (phase === 3) await thirdResponse
    expect(route.request().postDataJSON().protocolVersion).toBe(2)
    const input = route.request().postDataJSON().dataset
    await route.fulfill({ json: { protocolVersion: 2, model: 'mocked-model-for-e2e', choices: [{ message: { content: JSON.stringify({ themes: [{ id: 'thermal', aspectId: 'thermal', productId: input.products[0].productId, market: input.products[0].market, label: '发热', sentiment: 'mixed', quotes: [{ reviewId: input.reviews[0].reviewId, field: 'body', quote: 'charger gets hot', start: 0, end: 16 }] }], complianceRisks: [] }) } }] }, headers: { 'X-Qling-Prompt-Version': 'e2e-prompt/2', 'Access-Control-Allow-Origin': '*', 'Access-Control-Expose-Headers': 'X-Qling-Prompt-Version' } })
  })
  await page.getByRole('checkbox', { name: /同意本次在线处理/ }).check()
  await page.getByRole('button', { name: '运行百炼增强' }).click()
  await expect(page.getByRole('heading', { name: '市场机会，不止一个分数。' })).toBeVisible()
  await expect(page.getByText('混合 · 语义待复核').first()).toBeVisible()
  await page.getByRole('button', { name: /发热 混合/ }).first().click()
  await expect(page.getByRole('dialog')).toContainText('UTF-16 [0, 16)')
  await expect(page.getByRole('dialog').locator('mark')).toHaveText('charger gets hot')
  await page.keyboard.press('Escape')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(1)
  await expect(page.locator('.history-list li')).toContainText('在线增强')
  const runEvent = page.waitForEvent('download')
  await page.getByRole('button', { name: '下载分析存档' }).click()
  const run = JSON.parse(await readFile((await (await runEvent).path())!, 'utf8'))
  expect(run.report.analysisVersion.model).toBe('mocked-model-for-e2e')
  expect(run.report.analysisVersion.prompt).toBe('e2e-prompt/2')
  expect(run.report.themes[0].evidence[0].quoteAnchor.quote).toBe('charger gets hot')
  phase = 2
  await page.getByRole('button', { name: '运行百炼增强' }).click()
  await expect(page.getByText('已回退本地规则', { exact: true })).toBeVisible()
  await expect(page.locator('.history-list li')).toHaveCount(2)
  await expect(page.locator('.history-list li').first()).toContainText('在线失败后的本地回退')
  phase = 3
  const before = call
  await page.getByRole('button', { name: '运行百炼增强' }).click()
  await expect.poll(() => call).toBe(before + 1)
  await page.evaluate(() => window.scrollTo(0, 0))
  const cancelledRequest = page.waitForEvent('requestfailed', (request) => request.url().endsWith('/api/analyze'))
  await page.getByRole('button', { name: '欧盟', exact: true }).click()
  await expect(page.getByRole('button', { name: '欧盟', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await cancelledRequest
  releaseThird()
  await expect(page.getByRole('definition').filter({ hasText: '本地规则' })).toBeVisible()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await expect(page.locator('.history-list li')).toHaveCount(2)
})
