import { openAdvanced, analyzeAndOpenReport } from './advanced-controls'
import { test, expect, type Page } from '@playwright/test'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'

async function prepare(page: Page) {
  await page.route('**/health', route => route.fulfill({ json: { providerConfigured: false } }))
  await page.goto('/')
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  const products = 'productId,title,market,currency,price,capturedAt\nSKU,Sample charger,US,USD,30,2026-10-06'
  const reviews = 'reviewId,productId,locale,rating,body,reviewedAt\nR1,SKU,en-US,2,charger gets hot,2026-10-06'
  for (const [label, csv] of [['商品 CSV', products], ['评论 CSV', reviews]]) await page.getByLabel(label, { exact: true }).setInputFiles({ name: `${label}.csv`, mimeType: 'text/csv', buffer: Buffer.from(csv) })
  await page.getByRole('button', { name: '读取字段', exact: true }).click()
  await page.getByLabel('products-productId').waitFor()
  await page.getByRole('button', { name: '校验并预览' }).click()
  await page.getByRole('checkbox', { name: /我有权使用这些数据/ }).check()
  await page.getByRole('button', { name: '确认导入工作区' }).click()
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await analyzeAndOpenReport(page)
  await expect(page.getByText('分析存档已保存到本机')).toBeVisible()
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(page.getByRole('button', { name: '创建并保存验证任务' })).toBeEnabled()
}

async function fillTask(page: Page, title = '散热对照验证') {
  await page.getByLabel('验证任务标题').fill(title)
  await page.getByLabel('任务设计假设').fill('散热材料变更可能改善体验，尚未验证')
  await page.getByLabel('任务待验证指标').fill('记录双方温升与使用体验；门槛由用户定义')
  await page.getByLabel('任务验证方法', { exact: true }).selectOption('prototype')
  await page.getByLabel('任务验证步骤').fill('相同环境和负载比较两种样机，记录全部结果')
}

async function download(page: Page, name: string | RegExp) {
  const event = page.waitForEvent('download')
  await page.getByRole('button', { name }).click()
  return readFile((await (await event).path())!, 'utf8')
}

test('validation tasks retain original evidence, revisions and attachments across refresh, exports and backup restore', async ({ page, context }) => {
  const outDir = resolve(`artifacts/product-improvement/validation-tasks-${Date.now()}`)
  await mkdir(outDir, { recursive: true })
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await prepare(page)
  await fillTask(page)
  await page.getByRole('button', { name: '创建并保存验证任务' }).click()
  const panel = page.getByRole('region', { name: '改良验证任务' })
  const card = panel.getByRole('article', { name: '验证任务 散热对照验证', exact: true })
  await expect(card).toContainText('待验证')
  await card.getByLabel('任务状态', { exact: true }).selectOption('verified')
  await card.getByLabel('任务采用决定').selectOption('adopted')
  await card.getByLabel('任务本次理由').fill('不能跳过验证中')
  await card.getByLabel('任务结果记录').fill('合成结果')
  await card.getByRole('button', { name: '保存任务状态与结果' }).click()
  await expect(card.getByRole('alert')).toContainText('未保存')
  await card.getByLabel('任务状态', { exact: true }).selectOption('running')
  await card.getByLabel('任务本次理由').fill('开始样机对照；合成演示，不是实际验证')
  await card.getByLabel('任务结果记录').fill('')
  await card.getByRole('button', { name: '保存任务状态与结果' }).click()
  await expect(card.getByRole('heading')).toContainText('验证中')
  await card.getByLabel('任务结果附件').setInputFiles({ name: 'synthetic-result.txt', mimeType: 'text/plain', buffer: Buffer.from('Synthetic comparison only; not a seller validation.') })
  await expect(card.getByText('待保存附件 1 个')).toBeVisible()
  await card.getByLabel('任务状态', { exact: true }).selectOption('verified')
  await card.getByLabel('任务采用决定').selectOption('adopted')
  await card.getByLabel('任务结果记录').fill('合成用户记录：达到自设门槛，未独立核验')
  await card.getByLabel('任务本次理由').fill('<script>taskAttack()</script>采用仍为用户假设')
  await card.getByRole('button', { name: '保存任务状态与结果' }).click()
  await expect(card.getByRole('heading')).toContainText('已验证')
  await fillTask(page, '未采用方案')
  await page.getByRole('button', { name: '创建并保存验证任务' }).click()
  const rejected = panel.getByRole('article', { name: '验证任务 未采用方案', exact: true })
  await rejected.getByLabel('任务状态', { exact: true }).selectOption('running')
  await rejected.getByLabel('任务本次理由').fill('开始核对')
  await rejected.getByRole('button', { name: '保存任务状态与结果' }).click()
  await expect(rejected.getByRole('heading')).toContainText('验证中')
  await rejected.getByLabel('任务状态', { exact: true }).selectOption('rejected')
  await rejected.getByLabel('任务本次理由').fill('合成演示：不满足自设门槛')
  await rejected.getByLabel('任务结果记录').fill('合成结果不支持假设')
  await rejected.getByRole('button', { name: '保存任务状态与结果' }).click()
  await expect(rejected.getByRole('heading')).toContainText('已否定')
  const original = JSON.parse(await download(page, '导出证据 JSON'))
  expect(original.schemaVersion).toBe('1.6')
  expect(original.validationTasks.records).toHaveLength(6)
  expect(original.validationTasks.latest.map((task: { decision: string }) => task.decision).sort()).toEqual(['adopted', 'not-adopted'])
  await page.reload()
  await openAdvanced(page, '工作区设置')
  await openAdvanced(page, '仅替换演示评论')
  await openAdvanced(page, '字段映射模板')
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(card.getByRole('heading')).toContainText('已验证')
  expect(await download(page, '下载原结果附件')).toContain('Synthetic comparison only')
  const restored = JSON.parse(await download(page, '导出证据 JSON'))
  expect(restored.validationTasks.digest).toBe(original.validationTasks.digest)
  const widths = []
  for (const width of [320, 390, 768, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    const measurement = await page.evaluate(() => ({ scroll: document.documentElement.scrollWidth, client: document.documentElement.clientWidth }))
    expect(measurement.scroll).toBe(measurement.client)
    widths.push({ width, ...measurement })
    if ([390, 1280].includes(width)) await card.screenshot({ path: `${outDir}/task-${width}.png`, style: '.topbar { visibility: hidden; }' })
  }
  const html = await download(page, /导出高管备忘录/)
  const memo = await context.newPage()
  await memo.setContent(html)
  expect(await memo.locator('script,svg,[onerror],[onclick]').count()).toBe(0)
  await expect(memo.locator('body')).toContainText('<script>taskAttack()</script>')
  await expect(memo.locator('body')).toContainText(original.validationTasks.digest)
  await expect(memo.locator('body')).toContainText('相同环境和负载比较两种样机')
  await memo.getByRole('heading', { name: '采用与未采用的验证方案' }).scrollIntoViewIfNeeded()
  await memo.screenshot({ path: `${outDir}/memo.png` })
  await page.emulateMedia({ media: 'print' })
  const summary = page.getByRole('region', { name: '验证方案与结果报告' })
  await expect(summary).toBeVisible()
  await expect(summary).toContainText(original.validationTasks.digest)
  await summary.screenshot({ path: `${outDir}/print.png` })
  await page.emulateMedia({ media: 'screen' })
  const backup = await download(page, '导出工作区 JSON 备份')
  expect(JSON.parse(backup).schemaVersion).toBe('qling-workspace-backup/5')
  await page.getByRole('button', { name: /数据准备/ }).click()
  await openAdvanced(page, '仅替换演示评论')
  await page.getByRole('button', { name: '恢复默认数码快充样例' }).click()
  await page.getByLabel('恢复工作区备份').setInputFiles({ name: 'tasks.json', mimeType: 'application/json', buffer: Buffer.from(backup) })
  await page.getByRole('button', { name: /决策报告/ }).click()
  await openAdvanced(page, '比较两个历史版本')
  await page.getByRole('button', { name: '查看历史报告' }).click()
  await openAdvanced(page, '评论语义人工复核')
  await openAdvanced(page, '验证任务（高级）')
  await openAdvanced(page, '已保存概念图')
  await expect(card.getByRole('heading')).toContainText('已验证')
  expect(await download(page, '下载原结果附件')).toContain('Synthetic comparison only')
  const reassigned = JSON.parse(await download(page, '导出证据 JSON'))
  expect(reassigned.validationTasks.digest).not.toBe(original.validationTasks.digest)
  expect(reassigned.validationTasks.latest[0].anchor).toEqual(original.validationTasks.latest[0].anchor)
  expect(errors).toEqual([])
  await writeFile(`${outDir}/render-check.json`, JSON.stringify({ outDir, widths, errors, source: 'synthetic data, offline, simulated viewports and print; not seller validation' }, null, 2), { flag: 'wx' })
  console.log(`Validation task render evidence: ${outDir}`)
})

test('failed task save remains unsaved, blocks incomplete export and can be backed up and retried', async ({ page }) => {
  await prepare(page)
  await fillTask(page)
  await page.evaluate(() => {
    const original = IDBObjectStore.prototype.add
    Reflect.set(window, 'restoreTaskAdd', () => { IDBObjectStore.prototype.add = original })
    IDBObjectStore.prototype.add = function (...args) {
      if (this.name === 'validationTasks') throw new DOMException('Quota full', 'QuotaExceededError')
      return original.apply(this, args)
    }
  })
  await page.getByRole('button', { name: '创建并保存验证任务' }).click()
  const panel = page.getByRole('region', { name: '改良验证任务' })
  await expect(panel.getByText(/任务未保存/)).toBeVisible()
  await expect(panel.getByRole('article')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '导出证据 JSON' })).toBeDisabled()
  const failed = JSON.parse(await download(page, '下载未保存任务备份'))
  expect(failed.saved).toBe(false)
  expect(failed.record.plan.title).toBe('散热对照验证')
  expect(failed.previousFiles).toEqual([])
  await page.evaluate(() => Reflect.get(window, 'restoreTaskAdd')())
  await page.getByRole('button', { name: '重试保存任务' }).click()
  await expect(panel.getByRole('article')).toHaveCount(1)
  await expect(page.getByRole('button', { name: '导出证据 JSON' })).toBeEnabled()
})
